### ISSUE TITLE
Uploaded Image through Caldera Form for CiviCRM cannot be previewed

### ISSUE THREAD

**Issue by clement888** [mecachisenros/caldera-forms-civicrm#64] opened 2018-04-18 04:07 UTC
Hello there,

    I was trying out the file upload field of caldera form for civicrm to upload a image. the result was that the preview image cannot be shown in the summary/preview of image but is displayed properly when the contact is being edited.  i checked the image URL for both the preview and during edit, and apparantly they are different:

Preview URL: (broken)
https://www.example.com/civicrm?page=CiviCRM&q=civicrm/file&reset=1&id=18&eid=62

Image URL: (OK)
https://www.example.com/wp-admin/admin.php?page=CiviCRM&q=civicrm/file&reset=1&id=19&eid=62

any advise on how this can be corrected?  Thanks.

**Comment by mecachisenros** [comment] 2018-04-19 13:06
@clement888 could you upload an export of the form here (in json format) and specify your WP, CiviCRM, Caldera Forms (CF), and Caldera Forms CiviCRM (CFC) integration versions?

It's difficult to tell what it's going on and where to look, ie. is this a custom field or a core field, and on what entity (Activity, Contact, Note)?

**Comment by clement888** [comment] 2018-04-20 08:03
Hello,

  Thanks for your help.  I have included the json file below.

  The field used here is a custom field for files within a contact.  the versions of the relevant software are:

Wordpress -  4.9.5
Civicrm - 4.7.29
Caldera Form - 1.5.9.1
Caldera for Civicrm - 0.4.2


After uploading, the image is shown like this in the contact summary:



but if i set to edit for the custom field, it becomes correct:


Thanks for your help!

Clement

**Comment by mecachisenros** [comment] 2018-04-20 09:06
@clement888 looks like when commenting from email, attachments and github doesn't process them, see below:
![capture](https://user-images.githubusercontent.com/3038096/39042297-5f47112e-4482-11e8-8472-311065b92792.JPG)

**Comment by clement888** [comment] 2018-06-25 08:42
Hello there,

  just to follow up on this issue, i have looked at the link to the uploaded file for both views are different.  

I have uploaded a image file to be part of the record through Caldera form and tested to see whether there links to the image file is the same.

The broken link in the Summary View is:

https://1234.churchsys.info/civicrm?page=CiviCRM&q=civicrm/file&reset=1&id=22&eid=503

  but the file is rendered properly when we edit the field and the image file’s location is this:

https://1234.churchsys.info/wp-admin/admin.php?page=CiviCRM&q=civicrm/file&reset=1&id=23&eid=503

  Can you advise ? Thanks.

Clement

**Comment by kcristiano** [comment] 2018-10-09 15:09
@mecachisenros Have you had a chance to look at this?  I expect the file is getting the front end URL as it's being uploaded on the _front end_   Can we store the relative path and let CiviCRM determine how to display?

**Comment by mecachisenros** [comment] 2018-10-09 16:06
@kcristiano are you able to reproduce this? I haven't been able to, the URL in the form entry summary is the front end url, unless I'm misunderstanding something.

**Comment by kcristiano** [comment] 2018-10-09 16:49
@mecachisenros yes I can reproduce.   I'll send you a site you can see this on

**Comment by mecachisenros** [comment] 2018-10-09 17:08
Right, Summary view == Contact Summary!

I'll review and report back, I thought this was referring to the _Summary_ in CF's Entry viewer.

**Comment by mecachisenros** [comment] 2018-10-12 03:01
This should be fixed via aea6aa25848472d3611189762f2d5930f70fb8ff.

**Comment by mecachisenros** [comment] 2018-10-15 09:54
@clement888 this should be fixed on master branch, **but** as per current Civi version (5.6) there's still an underlying issue where custom Civi File fields are created twice when submitted through CFC, the issue has been addressed in this [PR](https://github.com/civicrm/civicrm-core/pull/12931), so I suggest you apply the patch to your Civi instance and pull/download latest master branch.

**Closed by mecachisenros** 2018-10-15 09:54 UTC
Labels: bug, fixed, needs feedback

**Comment by clement888** [comment] 2018-10-16 09:20
Hello Andrei,
 
   thanks for following up with this.  i have upgraded 0.4.4 onto my CIVICRM 5.3.2 on Wordpress and it works.  uploaded files thru caldera forms now render properly in the contact summary.  thanks again.

   i read the other issue you mentioned on file fields being created twice above, what would be the impact if i do not upgrade civicrm to 5.6 ?  thanks.

clement

**Comment by mecachisenros** [comment] 2018-10-21 14:33
@clement888 the impact would be that each File uploaded through CFC will be duplicated (two entries in `civicrm_file` and `civicrm_entity_file` tables, and two files in the upload folder). So if you don't mind that... 

By the way, I believe the patch will make it into CiviCRM 5.8 so version 5.6/5.7 are still affected.

You could apply the patch to your current install without upgrading Civi, as per [this](https://civicrm.stackexchange.com/a/4626/872) StackExchange answer:

```
cd path/to/civicrm
wget https://github.com/civicrm/civicrm-core/pull/12931.diff
patch -p1 < 12931.diff
rm 12931.diff 
```
`12931` being the PR I referenced above.
