### ISSUE TITLE
Create activity assigned to user

### ISSUE THREAD

**Issue by twomice** [mecachisenros/caldera-forms-civicrm#61] opened 2018-01-28 21:16 UTC
I'm trying to have my Caldera form create a CiviCRM activity which is assigned to the logged in user.

I've got activity creation working (see the attached Caldera form, [test1-export.json.txt](https://github.com/mecachisenros/caldera-forms-civicrm/files/1671619/test1-export.json.txt)). But is there any way to make it be assigned to the logged in user?

**Comment by mecachisenros** [comment] 2018-01-30 00:33
@twomice latest commit 5392f986465715b8f89b705e365ed8669d7a6851 should address your case.

You'll find three new checkboxes (for Target, Source, and Assignee) in the Activity processor, as well as `select2` widgets for the same fields at the bottom :)

I haven't fully tested it, so feedback is highly appreciated.

**Comment by twomice** [comment] 2018-03-09 01:25
Hi @mecachisenros. Am I using this functionality correctly? The attached very simple form ([form2-export.json.txt](https://github.com/mecachisenros/caldera-forms-civicrm/files/1795327/form2-export.json.txt)) has two processors:

- Contact processor ("Contact 1"): Has "Auto populate contact data with CiviCRM data if user is logged in. (Only for the first contact processor)" enabled. (I'm expecting this will make Contact 1 to be the contact for the logged in user.)
- Activity processor: Linked to "Contact 1", and checked all three boxes:
  - Set the Target (With contact) to the contact linked to this activity.
  - Set the Source (Added by) to the contact linked to this activity.
  - Set the Assignee (Assigned to) to the contact linked to this activity.

But when I submit the form, I get the fatal error "Mandatory key(s) missing from params array: source_contact_id".

I assumed Contact 1 would be the contact for the logged-in user, and that the Activity Source Contact would be that contact.  Am I doing it wrong?

**Comment by mecachisenros** [comment] 2018-03-09 11:32
@twomice I've just tested the `form2` attached but it has no contact processor, that's why you get a `missing mandatory key` error as there's no `contact_id` passed to the Activity processor, all entities Activity, Relationship, Case, Group, etc. relay on the Contact processor and they **must** be linked to a Contact processor.

See attached this example [activity-example-export.json.txt](https://github.com/mecachisenros/caldera-forms-civicrm/files/1796685/activity-example-export.json.txt) and let me know how it goes.

**Comment by twomice** [comment] 2018-03-09 14:37
@mecachisenros Actually "Form2" does have a Contact processor (it's the one with id="fp_6509988" in the json), but your example suggests something that "Form2" is missing: actual form fields for the contact's name and email, which are then used in the relevant fields of the Contact processor.

So I tried adding these to my "Form 2", and got good results.

So, 2 questions:

1. Am I right to guess that we need to have those form fields, and to have their values inserted into the right fields in the Contact processor, in order for the "Auto populate contact data with CiviCRM data if user is logged in." to result in creation of a CiviCRM contact?

2. If I have two Contact processors on a form, can I use an Activity processor to create an activity that's "with" Contact 1 and "assigned to" Contact 2?

**Comment by mecachisenros** [comment] 2018-03-12 19:56
@twomice for some reason the Contact processor didn't show up when I've imported your form.

Back to tour questions:
1. Yes you are correct, the form fields need to be *mapped* to the Civi fields in the processor, for both, autopopulation of data (if user is logged in or via checksum), and for Contact creation/update, if those fields ar not mapped, no contact will be created (nor any other entity linked to that Contact processor) as you'll be passing no values to Civi's API, so summarizing, what the processors do is map the form values to Civi's entities through the API if that makes sense.

2. That's not possible currently, I have not thought of that use case. I think a decorator on the select2 widget (the entityRef-like fields) to add the option to select/link to a Contact processor **and** the option to set a spcifc Civi contact would be a solution, and I would get rid of the checkboxes at the top, as they would not be needed anymore. Thoughts?

**Comment by twomice** [comment] 2018-03-12 21:04
@mecachisenros 
1. Got it. Thanks.

2. Yes, I think that's exactly the right way: _a decorator on the select2 widget (the entityRef-like fields) to add the option to select/link to a Contact processor and the option to set a spcifc Civi contact._

**Comment by mecachisenros** [comment] 2018-03-15 09:47
@twomice latest commit against master 93b13f859f0a8ce0401ec10636ced91b62c766a4 should address this. I suggest you clear browser cache.

Let me know if that works.

**Comment by twomice** [comment] 2018-03-15 15:11
Super -- will try. Thanks!

**Comment by twomice** [comment] 2018-03-20 23:37
Hi @mecachisenros With the latest code, I'm seeing that the Contact ID options (Target Contact ID; Source Contact ID; Assignee Contact ID) are all empty. I'm attaching the form json for reference:
[example_issue_61-export.json.txt](https://github.com/mecachisenros/caldera-forms-civicrm/files/1831592/example_issue_61-export.json.txt)

I'm also getting a JavaScript error which seems to be relevant:

```
Uncaught ReferenceError: cfc_select2_defaults is not defined
(anonymous function) @ VM1111:24
(anonymous function) @ VM1111:23
i @ jquery.js?ver=1.12.4:2
j.fireWith @ jquery.js?ver=1.12.4:2
n.extend.ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
```

... even though the admin.js file seems to be loaded correctly:
http://[example.com]/wp-content/plugins/caldera-forms-civicrm/assets/js/admin.js?ver=0.4.2
```
function cfc_contact_link_options( id = null ) {

	var options = [];
	for ( var i = 1; i <= 10; i++ ) {
		options.push( { id: 'contact_' + i, text: 'Contact ' + i } )
	}
	
	if( ! id ) return options;

	return options.filter( function( option ) {
		return option.id == id;
	} ).shift();
}

function cfc_select2_defaults( selector, value ) {

	if ( value ) {
...etc...
```

Can you suggest something I can do on my side, or is this an issue in the code that you can address?

Thanks,
Allen

**Comment by mecachisenros** [comment] 2018-03-26 12:13
@twomice I don't see what can be wrong, I've just tested on a clean Civi/WP install to double check, but I cannot reproduce the error. 

There was a _missing_ semicolon but that shouldn't have affected it, I've created a new release, can you try pulling master again, with the version bump WP should load a fresh copy of the `admin.js` file.

Also, can you check the call stack to see where/what might be causing it, maybe another plugin or `select2` version (the latter is more unlikely, I've address it a few commits back, but it can be a possibility).

**Comment by twomice** [comment] 2018-03-26 15:39
Thanks, I'll look at it again.

**Comment by danaskallman** [comment] 2018-03-26 17:17
Just to make sure I am understanding correctly, am including screenshot of the select assign to contact in the processor. I added two contacts to a form, and added the activity processor and used the following to assign to contact 1 and 2. Is that the goal?

![activity-contact-connection](https://user-images.githubusercontent.com/1139085/37921488-fb964890-30f7-11e8-8050-759ebd3ec7e5.png)

**Comment by twomice** [comment] 2018-03-26 17:31
@mecachisenros Yes, that's what I expected to see. So it looks like the issue is that those three select2 controls are not being populated at all, probably due to whatever is causing that JS error. I'll look further and update the ticket here.

**Comment by twomice** [comment] 2018-03-28 04:34
@mecachisenros OK, found the cause of the error. It was actually caused by an older browser lacking support for ES6-style default parameters. See https://github.com/twomice/caldera-forms-civicrm/commit/5007909c1689d75a8f2bfd350be192360b4f919b for the relevant line. This is an outdated browser, so I'm not submitting a PR; just documenting for posterity.

**Comment by twomice** [comment] 2018-03-28 04:47
@mecachisenros And, to report on the new feature: Yes, it works great and has the intended effect: I can configure an Activity Processor so that the Assigned, With, and Target contacts are all references to the contact in a Contact Processor. Thanks!
 
One small usability issue is not a deal-breaker for me, but reporting as feedback:
When selecting one of these contacts, as in this image
![selector](https://user-images.githubusercontent.com/759449/38009266-e63d0bf6-3218-11e8-9b52-6b83c2acd0ca.png)
I'm unable to select Contact 1 without first selecting another contact and then changing it back to Contact 1. I think that's because the selection is tied to the "change" event, and "Contact 1" is the default value. I.e., I have to select "Contact 2", then select "Contact 1".

**Comment by mecachisenros** [comment] 2018-04-11 10:08
@twomice Ha! You start using ES6 _new_ features and give them for granted... 

I'll amend both default parameter and usability issue in the next release.
Thank you for the feedback.

**Comment by twomice** [comment] 2018-04-11 15:40
:-)  Yeah, sad thing ES6 isn't so "new" anymore. But yeah, thanks for the continued improvements.

**Comment by mecachisenros** [comment] 2018-10-03 23:16
@twomice I've removed the default parameter, and the usability issue should be fixed as well.
Feel free to reopen if there's anything else missing.

**Closed by mecachisenros** 2018-10-03 23:16 UTC
Labels: enhancement
