### ISSUE TITLE
Install issue when there is no priceset

### ISSUE THREAD

**Issue by KilakwaBT** [mecachisenros/caldera-forms-civicrm#72] opened 2018-10-03 10:19 UTC
I installed version 0.4.4 with Caldera Forms 1.7.3 on a site that does not use price sets. I was looking to use the CiviCRM Contact reference field feature after seeing the demo by @danaskallman at CiviCamp Hartford. After activation I received an http 500 error. Reviewed the logs (see below) and saw it seemed to be looking for a price set. I added a simple price set and all is fine now.  Here are the log entries:

> [02-Oct-2018 20:42:22 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Price sets transient could not be set.' in /home/<<site>>/public_html/wp-content/plugins/caldera-forms-civicrm-0.4.4/includes/class-civicrm-caldera-forms-helper.php:639
Stack trace:
#0 /home/<<site>>/public_html/wp-content/plugins/caldera-forms-civicrm-0.4.4/fields/presets/class-civicrm-price-sets-presets.php(33): CiviCRM_Caldera_Forms_Helper->cached_price_sets()
#1 /home/<<site>>/public_html/wp-content/plugins/caldera-forms-civicrm-0.4.4/includes/class-civicrm-caldera-forms-fields.php(83): CiviCRM_Caldera_Forms_Price_Sets_Presets->__construct(Object(CiviCRM_Caldera_Forms))
#2 /home/<<site>>/public_html/wp-content/plugins/caldera-forms-civicrm-0.4.4/includes/class-civicrm-caldera-forms-fields.php(44): CiviCRM_Caldera_Forms_Fields->setup_objects()
#3 /home/<<site>>/public_html/wp-content/plugins/caldera-forms-civicrm-0.4.4/caldera-forms-civicrm.php(250): CiviCRM_Caldera_Forms_Fields->__construct(Object(CiviCRM_Caldera_Forms))
#4 /home/<<site>>/public_html/wp-content in /home/<<site>>/public_html/wp-content/plugins/caldera-forms-civicrm-0.4.4/includes/class-civicrm-caldera-forms-helper.php on line 639

**Comment by kcristiano** [comment] 2018-10-03 11:53
@KilakwaBT  I was not able to reproduce this on my local WP 5.9.8 and CiviCRM 5.7-alpha setup.   I did git checkouts of https://github.com/tadpolecc/Caldera-Forms  the default branch is 1.7.2.1 (displays as 1.7.3-a1 in the admin) and https://github.com/mecachisenros/caldera-forms-civicrm.git  (checked out 0.4.4 branch)

I then activated via wp-cli and received no errors.

I then copied the Folders (Caldera-Forms and caldera-forms-civicrm) to another site running WP 4.9.8 and CiviCRM 5.6-RC and activated via the admin.  Both plugins activated without errror.

Server is Apache 2.4.34, php 7.1.22

These are 'clean' installs.   Did I miss a step to reproduce?   Is there something unique about the site you had the error on?

**Comment by KilakwaBT** [comment] 2018-10-03 13:44
Two things about the site that this occurred on. 

- Both plugins were running in previous versions prior to moving to the most recent versions. I did delete them first and then reload via admin.
- Site is running PHP 5.6

I am going to try to set this up on a clean install later today to work with the new features. I'll update if trouble returns.

**Comment by mecachisenros** [comment] 2018-10-03 22:45
@KilakwaBT thank you for reporting, I'll test on a clean install and report back.

**Comment by kcristiano** [comment] 2018-10-13 12:30
@mecachisenros I ran into another 'edge case' related to this.  I updated to the master branch from 0.4.2.  I had immediate fatal errors.   As I updated from the command line, the errors only manifested when I ran a command.   

`cv ext:list -L`  threw
```
[Exception]
  Price sets transient could not be set.
```

`wp plugin deactivate caldera-forms-civicrm` threw
```
PHP Fatal error:  Uncaught Exception: Price sets transient could not be set. in /home/wpcmshos/public_html/wp-content/plugins/caldera-forms-civicrm/includes/class-civicrm-caldera-forms-helper.php:629
```

I was able to deactivate with `wp plugin deactivate caldera-forms0-civicrm --skip-plugins`

Upon logging in to the site, not only did I not have a price set, I could not add one as CiviContribute was disabled.  This site is an edge case, No Memberships, No Donations.   I enabled CiviContribute and added a simple Price Set and all was well.

While this edge case will be rare (almost no one will disable CiviContribute), not having a Price Set will be more common.  Especially for users that install CiviCRM, Caldera Forms and this plugin themselves.   

Let me know if you need help testing this further.

**Comment by mecachisenros** [comment] 2018-10-21 14:35
I'll close this, feel free to reopen if needed.

**Closed by mecachisenros** 2018-10-21 14:35 UTC
Labels: bug, fixed
