### ISSUE TITLE
Phone/Email won't appear if multiples of same location type

### ISSUE THREAD

**Issue by mcollopy** [mecachisenros/caldera-forms-civicrm#70] opened 2018-09-21 00:23 UTC
If phone Home:Landline and Home:Mobile are populated, the form returns blank.
Same as if 2 of the same location, email field is the same.
Is there a way to set the filter to Primary only?

**Comment by mecachisenros** [comment] 2018-10-03 23:13
@mcollopy thanks for reporting.

Can you elaborate on your environment CiviCRM version, WP version, Caldera Forms (CF) version, Caldera Forms CiviCRM (CFC) version?

I'm not able to reproduce the issue.

If a Contact has more than one phone/email for the same location **and** type ie two Home:Mobile the fields **won't auto populate** (auto fill when logged in or using a checksum link), this is a limitation in the way it's implemented, but that should not prevent the form from rendering/loading.

**Comment by mcollopy** [comment] 2018-10-04 00:16
CiviCRM 5.4.0
Wordpress Version 4.9.8
Caldera Forms Version 1.7.2
Caldera Forms CiviCRM Version 0.4.3

To replicate - create a form with a field 'Phone'
- add processor CiviCRM Contact 1
- enable Contact Phone
- select location 'Home' (or whatever location you have)
- add Magic Tag %phone%

On your contact record, edit to have only phone number e.g.
- location Home, type Mobile

Go to the form, see the phone field is pre-populated

Edit your contact record and add a 2nd phone e.g.
- location Home, type Landline (or other type for same location)

Go to the form, see the phone field is empty

Hope that helps.

**Comment by mecachisenros** [comment] 2018-10-04 01:11
Right, got you, that issue is fixed in the next release (CFC v0.4.4) which will be *released* very soon, you can update to the `master` branch or use the [0.4.4](https://github.com/mecachisenros/caldera-forms-civicrm/tree/0.4.4) branch.

**Comment by mecachisenros** [comment] 2018-10-14 19:29
@mcollopy I'll close this as for now, feel free to reopen if needed.

**Closed by mecachisenros** 2018-10-14 19:29 UTC
Labels: fixed, needs feedback

**Comment by mcollopy** [comment] 2018-10-15 00:28
Tested and working - was able to set the phone type, and now 'mobile' appears.
Great work, thanks for your support.
