### ISSUE TITLE
Various Invalid argument supplied for foreach() warnings from processors

### ISSUE THREAD

**Issue by seascoot** [mecachisenros/caldera-forms-civicrm#51] opened 2017-09-03 22:25 UTC
I'm getting a bunch or warnings and notices related to invalid arguments and undefined indexes when a page containing a Caldera form is loaded, even with no plugin processors active.
Here are the notices and call stacks fyi.

Warning | Invalid argument supplied for foreach() | 1 | wp-content/plugins/caldera-forms-civicrm/processors/contact/class-contact-processor.php:498 | CiviCRM_Caldera_Forms_Contact_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/contact/class-contact-processor.php:498apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
-- | -- | -- | -- | -- | --
1 | wp-content/plugins/caldera-forms-civicrm/processors/address/class-address-processor.php:128 | CiviCRM_Caldera_Forms_Address_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/address/class-address-processor.php:128apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
1 | wp-content/plugins/caldera-forms-civicrm/processors/email/class-email-processor.php:126 | CiviCRM_Caldera_Forms_Email_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/email/class-email-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
1 | wp-content/plugins/caldera-forms-civicrm/processors/phone/class-phone-processor.php:126 | CiviCRM_Caldera_Forms_Phone_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/phone/class-phone-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
1 | wp-content/plugins/caldera-forms-civicrm/processors/website/class-website-processor.php:126 | CiviCRM_Caldera_Forms_Website_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/website/class-website-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
1 | wp-content/plugins/caldera-forms-civicrm/processors/im/class-im-processor.php:126 | CiviCRM_Caldera_Forms_Im_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/im/class-im-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37
Undefined index: processors | 1 | wp-content/plugins/caldera-forms-civicrm/processors/contact/class-contact-processor.php:498 | CiviCRM_Caldera_Forms_Contact_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/contact/class-contact-processor.php:498apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
-- | -- | -- | -- | --
1 | wp-content/plugins/caldera-forms-civicrm/processors/address/class-address-processor.php:128 | CiviCRM_Caldera_Forms_Address_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/address/class-address-processor.php:128apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
1 | wp-content/plugins/caldera-forms-civicrm/processors/email/class-email-processor.php:126 | CiviCRM_Caldera_Forms_Email_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/email/class-email-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
1 | wp-content/plugins/caldera-forms-civicrm/processors/phone/class-phone-processor.php:126 | CiviCRM_Caldera_Forms_Phone_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/phone/class-phone-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
1 | wp-content/plugins/caldera-forms-civicrm/processors/website/class-website-processor.php:126 | CiviCRM_Caldera_Forms_Website_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/website/class-website-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37 | Plugin: woocommerce
1 | wp-content/plugins/caldera-forms-civicrm/processors/im/class-im-processor.php:126 | CiviCRM_Caldera_Forms_Im_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/im/class-im-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37

**Comment by mecachisenros** [comment] 2017-09-04 10:38
@seascoot can you report what Civi/WP/CF/CFC versions are you using as well the environment, I'm not able to reproduce the warnings.

**Comment by mecachisenros** [comment] 2017-09-04 11:38
@seascoot can you give a go at the latest master branch and let me know if the warnings are gone?

**Comment by seascoot** [comment] 2017-09-04 21:21
Environment is:
Wordpress: 4.8.1
Woocommerce: 3.1.2
CiviCRM: 4.7.23
Caldera Forms: 1.5.5
Caldera Forms Civicrm: 0.4.1

Sorry - I meant to come back to my original post and edit this in but fell down the rabbit hole of chasing another issue.

Will test the latest master in the next hour.

**Comment by seascoot** [comment] 2017-09-04 23:59
Using the latest master most of the warnings have gone.  The notice and warning related to the email processor is still there however.

I have also had an issue with Auto populate contact data.  I'm not sure if it is related so I'll open a different issue.

**Comment by mecachisenros** [comment] 2017-09-05 09:10
@seascoot what's the notice and warning related to the email processor?

**Comment by seascoot** [comment] 2017-09-05 19:31
PHP Error | Count | Location | Call Stack | Component
-- | -- | -- | -- | --
Warning | Invalid argument supplied for foreach() | 1 | wp-content/plugins/caldera-forms-civicrm/processors/email/class-email-processor.php:126 | CiviCRM_Caldera_Forms_Email_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/email/class-email-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37
-- | -- | -- | -- | --
Notice | Undefined index: processors | 1 | wp-content/plugins/caldera-forms-civicrm/processors/email/class-email-processor.php:126 | CiviCRM_Caldera_Forms_Email_Processor->pre_render()wp-content/plugins/caldera-forms-civicrm/processors/email/class-email-processor.php:126apply_filters('caldera_forms_render_get_form')wp-content/plugins/caldera-forms/classes/core.php:3965Caldera_Forms::render_form()wp-content/plugins/caldera-forms/classes/core.php:4670Caldera_Forms->shortcode_handler()Unknown locationdo_shortcode_tag()Unknown locationpreg_replace_callback()wp-includes/shortcodes.php:223do_shortcode()Unknown locationapply_filters('the_content')wp-includes/post-template.php:240the_content()wp-content/plugins/woocommerce/templates/single-product/tabs/description.php:33wc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:1126woocommerce_product_description_tab()Unknown locationwc_get_template()wp-content/plugins/woocommerce/includes/wc-template-functions.php:895woocommerce_output_product_data_tabs()Unknown locationdo_action('woocommerce_after_single_product_summary')wp-content/plugins/woocommerce/templates/content-single-product.php:79load_template('~/wp-content/plugins/woocommerce/templates/content-single-product.php')wp-content/plugins/woocommerce/includes/wc-core-functions.php:175wc_get_template_part()wp-content/plugins/woocommerce/templates/single-product.php:37
-- | -- | -- | --

**Comment by mecachisenros** [comment] 2017-09-08 09:08
@seascoot all warnings should be fixed with latest master.

I'll close this issue.

**Closed** 2017-09-08 09:08 UTC
