### ISSUE TITLE
Dedupe not working

### ISSUE THREAD

**Issue by mikaweinstein** [mecachisenros/caldera-forms-civicrm#45] opened 2017-07-06 14:04 UTC
I've tried with a few different Dedupe Rules and on two different sites, and in all cases the form submissions are creating duplicates.

**Comment by mecachisenros** [comment] 2017-07-06 14:18
@mikaweinstein what version of Civi, CF and CFC do you have installed?

**Comment by mikaweinstein** [comment] 2017-07-06 14:24
@mecachisenros 

On one site: CiviCRM 4.7.14, CF 1.5.2.1, CFC 0.4

On the other site: CiviCRM 4.7.10, CF 1.5.2.1, CFC 0.4

**Comment by mecachisenros** [comment] 2017-07-06 14:42
@mikaweinstein can you export the form in question and upload it here?
I'm not able to reproduce the issue, so it might be something specific to the form.

**Comment by mikaweinstein** [comment] 2017-07-06 14:49
I tried it with two custom forms on the first site, and the standard "Contact Form" template on the second site. Export of standard form here:

[contact-us-export.json.zip](https://github.com/mecachisenros/caldera-forms-civicrm/files/1128216/contact-us-export.json.zip)

**Comment by mecachisenros** [comment] 2017-07-06 19:43
@mikaweinstein this should be fixed against the master branch, thank you for reporting the bug.

I missed something refactoring. Also the form you attached didn't had an email location set, now the processor will have one selected by default, without the option to leave it empty or forget to set it.

**Closed** 2017-07-06 19:43 UTC

**Comment by mikaweinstein** [comment] 2017-07-06 19:51
@mecachisenros Thank you so much!
